# worfklow name (override name defined on the RO-Crate metadata)
# name: MyWorkflow
# worfklow visibility
public: False

# Issue Checker Settings
issues:
  # Enable/Disable issue checker
  # The list of issue types can be found @ <LIFEMONITOR_API_URL>/workflows/issues
  # (e.g., https://api.lifemonitor.eu/workflows/issues)
  check: true
  # csv of issues to check (all included by default)
  # include: [missing_config_file, not_initialised_repository_issue, missing_workflow_file, missing_metadata_file, missing_ro_crate_workflow_file, outdated_metadata_file, missing_workflow_name]
  # csv of issues to ignore (none ignored by default)
  # exclude: [missing_config_file, not_initialised_repository_issue, missing_workflow_file, missing_metadata_file, missing_ro_crate_workflow_file, outdated_metadata_file, missing_workflow_name]
    

# Github Integration Settings
push:
  branches:
    # Define the list of branches to watch
    # - name: feature/XXX               # wildcards can be used to specify branches (e.g., feature/*)
    #   update_registries: ["wfhubdev"] # available registries are listed
    #                                   # by the endpoint `<lifemonitor_url>/registries`
    #                                   # (e.g., https://api.lifemontor.eu/registries)
    - name: "main"
      update_registries: []
      enable_notifications: true
    # - name: "develop"
    #   update_registries: []
    #   enable_notifications: true

  tags:
    # Define the list of tags to watch
    # - name: v*.*.*                    # wildcards can be used to specify tags (e.g., feature/*)
    #   update_registries: ["wfhub"]    # available registries are listed
    #                                   # by the endpoint `<lifemonitor_url>/registries`
    #                                   # (e.g., https://api.lifemontor.eu/registries)
    - name: "v*.*.*"
      update_registries: [wfhubdev, wfhubprod]
      enable_notifications: true
    - name: "*.*.*"
      update_registries: [wfhubdev, wfhubprod]
      enable_notifications: true