version: "3.5"

services:
  nginx:
    image: bitnami/nginx:1.19-debian-10
    depends_on:
      - "lm"
    ports:
      - "8443:8443"
    restart: "always"
    networks:
      - life_monitor
    volumes:
      - "./certs:/nginx/certs:ro"
      - "./docker/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/lm.conf:ro"
      - "lifemonitor_static_files:/app/lifemonitor/static:ro"
      - "lifemonitor_specs:/app/specs:ro"
