version: "3"

services:

  db:
    # Docker image docs: https://github.com/bitnami/bitnami-docker-postgresql
    # We use PgSQL 11 instead of 12 since that's the newest version of the client
    # available in the Python image we're using for the application
    image: bitnami/postgresql:11
    ports:
      - "5432"
    env_file: &env_file
      - settings.conf
    environment:
      - 'ALLOW_EMPTY_PASSWORD=no'
    restart: "always"
    healthcheck:
        test: [ "CMD", "pg_isready" ]
        interval: "15s"
        retries: 5
    volumes:
      - 'lifemonitor_db:/bitnami/postgresql'

  lm:
    # Remember that this service is using its default configuration
    # to access the database, so the settings must match the environment
    # configuration set for db above.
    image: crs4/lifemonitor
    depends_on:
      - "db"
    ports:
      - "8080:8080"
    #DEV user: "USER_UID:USER_GID"
    env_file: *env_file
    environment:
      - "DEV=false"
      - "POSTGRESQL_HOST=db"
    #DEV   - "HOME=/lm"
    #DEV volumes:
    #DEV   - "LOCAL_PATH/lifemonitor:/lm/lifemonitor"
 
volumes:
  lifemonitor_db:
