version: "3.5"

services:

  nginx:
    image: bitnami/nginx:1.19-debian-10
    depends_on:
      - "lm"
    ports:
      - "8443:8443"
    restart: "always"
    networks:
      - life_monitor
    volumes:
      - "./certs:/nginx/certs:ro"
      - "./docker/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/lm.conf:ro"

  db:
    # Docker image docs: https://github.com/bitnami/bitnami-docker-postgresql
    # We use PgSQL 11 instead of 12 since that's the newest version of the client
    # available in the Python image we're using for the application
    image: bitnami/postgresql:11
    ports:
      - "5432"
    env_file: &env_file
      - settings.conf
    environment:
      - 'ALLOW_EMPTY_PASSWORD=no'
    restart: "always"
    healthcheck:
      test: "pg_isready -U $${POSTGRESQL_USERNAME}"
      interval: "10s"
      retries: 6
    networks:
      - life_monitor
    volumes:
      - 'lifemonitor_db:/bitnami/postgresql'

  lm:
    # Remember that this service is using its default configuration
    # to access the database, so the settings must match the environment
    # configuration set for db above.
    image: crs4/lifemonitor
    restart: "always"
    depends_on:
      - "db"
      - "init"
    #DEV ports:
    #DEV  - "8000:8000"
    #DEV user: "USER_UID:USER_GID"
    env_file: *env_file
    environment:
      - "POSTGRESQL_HOST=db"
      - "POSTGRESQL_PORT=5432"
      - "FLASK_ENV=production"
    #DEV   - "HOME=/lm"
    volumes:
    #DEV   - "LOCAL_PATH:/lm"
      - "./certs:/certs:ro"
      - "./instance:/lm/instance:ro"
    networks:
      - life_monitor

  init:
    # Remember that this service is using its default configuration
    # to access the database, so the settings must match the environment
    # configuration set for db above.
    image: crs4/lifemonitor
    entrypoint: /bin/bash
    command: |
      -c "flask db init || exit 0"
    depends_on:
      - "db"
    #DEV user: "USER_UID:USER_GID"
    env_file: *env_file
    environment:
      - "POSTGRESQL_HOST=db"
      - "POSTGRESQL_PORT=5432"
      - "FLASK_ENV=production"
    #DEV   - "HOME=/lm"
    volumes:
    #DEV   - "LOCAL_PATH:/lm"
      - "./certs:/certs:ro"
      - "./instance:/lm/instance:ro"
    networks:
      - life_monitor

volumes:
  lifemonitor_db:

networks:
  life_monitor:
  # You can easily connect this docker-compose with a
  # local instance of the Seek/WorkflowHub docker-compose by putting them
  # both on the same Docker network.  The configuration below will
  # instantiate the life monitor services on a docker network called
  # `seek_default` (the default name used by seek) which is managed externally
  # (presumably by the docker-compose you used to start Seek).
  # See the docker-compose network configuration reference for more details.

  #   name: seek_default
  #   external: true
