version: "3.5"

services:

  nginx:
    image: bitnami/nginx:1.19-debian-10
    depends_on:
      - "lm"
    ports:
      - "8443:8443"
    restart: "always"
    networks:
      - life_monitor
    volumes:
      - "./certs:/nginx/certs:ro"
      - "./docker/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/lm.conf:ro"

  db:
    # Docker image docs: https://github.com/bitnami/bitnami-docker-postgresql
    # We use PgSQL 11 instead of 12 since that's the newest version of the client
    # available in the Python image we're using for the application
    image: bitnami/postgresql:11
    ports:
      - "5432"
    env_file: &env_file
      - settings.conf
    environment:
      - 'ALLOW_EMPTY_PASSWORD=no'
    restart: "always"
    healthcheck:
      test: "pg_isready -U $${POSTGRESQL_USERNAME}"
      interval: "10s"
      retries: 6
    networks:
      - life_monitor
    volumes:
      - 'lifemonitor_db:/bitnami/postgresql'

  lm:
    # Remember that this service is using its default configuration
    # to access the database, so the settings must match the environment
    # configuration set for db above.
    image: crs4/lifemonitor
    restart: "always"
    depends_on:
      - "db"
      - "init"
    #DEV ports:
    #DEV  - "8000:8000"
    #DEV user: "USER_UID:USER_GID"
    env_file: *env_file
    environment:
      - "POSTGRESQL_HOST=db"
      - "POSTGRESQL_PORT=5432"
      - "FLASK_ENV=production"
    #DEV   - "HOME=/lm"
    #DEV  # Normally, OAuthLib will raise an InsecureTransportError if you attempt to use OAuth2 over HTTP,
    #DEV  # rather than HTTPS. Setting this environment variable will prevent this error from being raised.
    #DEV  # This is mostly useful for local testing, or automated tests. Never set this variable in production.
    #DEV   - "AUTHLIB_INSECURE_TRANSPORT=1"
    volumes:
    #DEV   - "LOCAL_PATH:/lm"
      - "./certs:/certs:ro"
      - "./instance:/lm/instance:ro"
    #TEST   - "./tests/settings.conf:/lm/settings.conf:ro" # overwrite settings with test settings
    networks:
      - life_monitor

  init:
    # Remember that this service is using its default configuration
    # to access the database, so the settings must match the environment
    # configuration set for db above.
    image: crs4/lifemonitor
    entrypoint: /bin/bash
    command: |
      -c "wait-for-postgres.sh && flask db init"
    depends_on:
      - "db"
    #DEV user: "USER_UID:USER_GID"
    env_file: *env_file
    environment:
      - "POSTGRESQL_HOST=db"
      - "POSTGRESQL_PORT=5432"
      - "FLASK_ENV=production"
    #DEV  # Normally, OAuthLib will raise an InsecureTransportError if you attempt to use OAuth2 over HTTP,
    #DEV  # rather than HTTPS. Setting this environment variable will prevent this error from being raised.
    #DEV  # This is mostly useful for local testing, or automated tests. Never set this variable in production.
    #DEV   - "AUTHLIB_INSECURE_TRANSPORT=1"
    #DEV   - "HOME=/lm"
    volumes:
    #DEV   - "LOCAL_PATH:/lm"
      - "./certs:/certs:ro"
      - "./instance:/lm/instance:ro"
    #TEST   - "./tests/settings.conf:/lm/settings.conf:ro" # overwrite settings with test settings
    networks:
      - life_monitor

  #TEST seek:
  #TEST   image: crs4/lifemonitor-tests:seek
  #TEST   restart: "always"
  #TEST   ports:
  #TEST    - "3000:3000"
  #TEST   volumes:
  #TEST     - ./certs/lm.crt:/certs/lm.crt:ro
  #TEST     - ./certs/lm.key:/certs/lm.key:ro
  #TEST     - ./tests/config/registries/seek/nginx.conf:/etc/nginx/nginx.conf:ro 
  #TEST     #- ./tests/config/registries/seek/data/db.sqlite3:/seek/sqlite3-db/production.sqlite3:rw
  #TEST     #- ./tests/config/registries/seek/data/filestore:/seek/filestore:rw
  #TEST   networks:
  #TEST     - life_monitor

  #TEST jenkins:
  #TEST   image: crs4/lifemonitor-tests:jenkins
  #TEST   ports:
  #TEST     - 8080:8080
  #TEST     - 50000:50000
  

volumes:
  lifemonitor_db:

networks:
  life_monitor:
  # You can easily connect this docker-compose with a
  # local instance of the Seek/WorkflowHub docker-compose by putting them
  # both on the same Docker network.  The configuration below will
  # instantiate the life monitor services on a docker network called
  # `seek_default` (the default name used by seek) which is managed externally
  # (presumably by the docker-compose you used to start Seek).
  # See the docker-compose network configuration reference for more details.
    # 
    # name: seek_default
    # external: true

    # Uncomment the lines below to customize your network address
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 192.168.238.0/24