version: "3.5"

services:
  db:
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
  lm:
    entrypoint: /bin/bash
    command: |
      -c "sleep infinity"
    user: "${USER_UID}:${USER_GID}"
    environment:
      - "FLASK_ENV=development"
      - "TEMPLATES_AUTO_RELOAD=True"
      - "HOME=/lm"
      # Normally, OAuthLib will raise an InsecureTransportError if you attempt to use OAuth2 over HTTP,
      # rather than HTTPS. Setting this environment variable will prevent this error from being raised.
      # This is mostly useful for local testing, or automated tests. Never set this variable in production.
      - "AUTHLIB_INSECURE_TRANSPORT=1"
      # - "SERVER_NAME=lm:8000"
    volumes:
      - "./:/lm"
      - "/lm/lifemonitor/static/dist"
    ports:
      - "8000"

  init:
    user: "${USER_UID}:${USER_GID}"
    environment:
      - "FLASK_ENV=development"
      # Normally, OAuthLib will raise an InsecureTransportError if you attempt to use OAuth2 over HTTP,
      # rather than HTTPS. Setting this environment variable will prevent this error from being raised.
      # This is mostly useful for local testing, or automated tests. Never set this variable in production.
      - "AUTHLIB_INSECURE_TRANSPORT=1"
      - "HOME=/lm"
    volumes:
      - "./:/lm"
