version: "3.5"

services:
  redis:
    image: bitnami/redis:6.2
    ports:
      - "6379"
    env_file: &env_file
      - settings.conf
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
    networks:
      - life_monitor
    volumes:
      - "data_redis:/bitnami/redis/data"

volumes:
  data_redis:
