version: "3.5"

services:
  prometheus:
    image: prom/prometheus:v2.24.1
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - life_monitor

networks:
  life_monitor:
    name: life_monitor
