version: "3.5"

services:
  lmtests:
    image: crs4/lifemonitor
    user: "${USER_UID}:${USER_GID}"
    depends_on:
      - "db"
    env_file: ./settings.conf
    restart: "no"
    entrypoint: /bin/bash
    command: |
      -c "wait-for-postgres.sh && wait-for-redis.sh ./lm-admin db init && /usr/local/bin/lm_entrypoint.sh"
    environment:
      - "FLASK_ENV=testingSupport"
      - "HOME=/lm"
      # Normally, OAuthLib will raise an InsecureTransportError if you attempt to use OAuth2 over HTTP,
      # rather than HTTPS. Setting this environment variable will prevent this error from being raised.
      # This is mostly useful for local testing, or automated tests. Never set this variable in production.
      - "AUTHLIB_INSECURE_TRANSPORT=1"
      - "POSTGRESQL_HOST=db"
      - "POSTGRESQL_PORT=5432"
      - "TRAVIS_TESTING_SERVICE_URL=${TRAVIS_TESTING_SERVICE_URL}"
      - "TRAVIS_TESTING_SERVICE_TOKEN=${TRAVIS_TESTING_SERVICE_TOKEN}"
      - "TRAVIS_TESTING_SERVICE_TYPE=travis"
      - "GITHUB_TESTING_SERVICE_URL=https://github.com"
      - "GITHUB_TESTING_SERVICE_TOKEN=${GH_TESTING_SERVICE_TOKEN}"
      - "GITHUB_TESTING_SERVICE_TYPE=github"
      - "GITHUB_API_TESTING_SERVICE_URL=https://api.github.com"
      - "GITHUB_API_TESTING_SERVICE_TOKEN=${GH_TESTING_SERVICE_TOKEN}"
      - "GITHUB_API_TESTING_SERVICE_TYPE=github"
    volumes:
      - "./:/lm"
      - "./certs:/certs:ro"
      - "./instance:/lm/instance:ro"
      - "./settings.conf:/lm/settings.conf:ro" # default settings
    ports:
      - "8000"
    networks:
      - life_monitor

  webserver:
    image: crs4/lifemonitor-tests:webserver
    env_file: ./tests/settings.conf
    volumes:
      - "./tests/config/data:/data"
    ports:
      - "5000"
    networks:
      - life_monitor

networks:
  life_monitor:
    name: life_monitor
