services:
  db:
    # Docker image docs: https://github.com/bitnami/bitnami-docker-postgresql
    # We use PgSQL 11 instead of 12 since that's the newest version of the client
    # available in the Python image we're using for the application
    image: bitnami/postgresql:11
    ports:
      - "5432"
    env_file: &env_file
      - settings.conf
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
    restart: "unless-stopped"
    healthcheck:
      test: "pg_isready -U $${POSTGRESQL_USERNAME}"
      interval: "10s"
      retries: 6
    networks:
      - life_monitor
    volumes:
      - "data_db:/bitnami/postgresql"

  nginx:
    image: bitnami/nginx:1.19-debian-10
    depends_on:
      - "lm"
    ports:
      - "8443:8443"
    restart: "unless-stopped"
    healthcheck:
      test: >
        /bin/sh -c "http_code=$$(curl --insecure https://lm:8443/health -s -w %{http_code}); if [ $${http_code} -eq 502 ]; then exit 1; fi;"
      interval: "2s"
      retries: 3
      timeout: "1s"
    networks:
      - life_monitor
    volumes:
      - "./certs:/nginx/certs:ro"
      - "./docker/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/lm.conf:ro"
      - "data_static_files:/app/lifemonitor/static:ro"
      - "data_specs:/app/specs:ro"

  lm:
    # Remember that this service is using its default configuration
    # to access the database, so the settings must match the environment
    # configuration set for db above.
    image: crs4/lifemonitor
    restart: "unless-stopped"
    depends_on:
      - "db"
      - "init"
      - "redis"
    user: "${USER_UID}:${USER_GID}"
    env_file: *env_file
    environment:
      - "FLASK_ENV=production"
      - "POSTGRESQL_HOST=db"
      - "POSTGRESQL_PORT=5432"
      - "WEBSOCKET_SERVER=false"
    volumes:
      - "./certs:/certs:ro"
      - "./instance:/lm/instance:ro"
      - "./settings.conf:/lm/settings.conf:ro" # default settings
      - "data_workflows:/var/data/lm"
      - "/tmp/lifemonitor-logs:/var/log/lm"
    networks:
      - life_monitor

  init:
    # Remember that this service is using its default configuration
    # to access the database, so the settings must match the environment
    # configuration set for db above.
    image: crs4/lifemonitor
    entrypoint: /bin/bash
    restart: "no"
    command: |
      -c "wait-for-postgres.sh && ./lm-admin db init"
    depends_on:
      - "db"
    env_file: *env_file
    environment:
      - "FLASK_ENV=production"
      - "POSTGRESQL_HOST=db"
      - "POSTGRESQL_PORT=5432"
    volumes:
      - "./certs:/certs:ro"
      - "./instance:/lm/instance:ro"
      - "./settings.conf:/lm/settings.conf:ro" # default settings
      - "data_workflows:/var/data/lm"
      - type: volume
        source: data_static_files
        target: /lm/lifemonitor/static
      - type: volume
        source: data_specs
        target: /lm/specs
    networks:
      - life_monitor

  worker:
    image: crs4/lifemonitor
    entrypoint: /usr/local/bin/worker_entrypoint.sh
    restart: "unless-stopped"
    depends_on:
      - "db"
      - "init"
      - "redis"
    user: "${USER_UID}:${USER_GID}"
    env_file: *env_file
    environment:
      - "FLASK_ENV=production"
      - "POSTGRESQL_HOST=db"
      - "POSTGRESQL_PORT=5432"
      - "WEBSOCKET_SERVER=false"
    volumes:
      - "./certs:/certs:ro"
      - "./instance:/lm/instance:ro"
      - "./settings.conf:/lm/settings.conf:ro" # default settings
      - "data_workflows:/var/data/lm"
    networks:
      - life_monitor

  ws_server:
    image: crs4/lifemonitor
    entrypoint: /usr/local/bin/wss-entrypoint.sh
    restart: "unless-stopped"
    depends_on:
      - "db"
      - "init"
      - "redis"
    user: "${USER_UID}:${USER_GID}"
    env_file: *env_file
    environment:
      - "FLASK_ENV=production"
      - "WEBSOCKET_SERVER=true"
      - "POSTGRESQL_HOST=db"
      - "POSTGRESQL_PORT=5432"
      - "LIFEMONITOR_TLS_KEY=/certs/lm.key"
      - "LIFEMONITOR_TLS_CERT=/certs/lm.crt"
    volumes:
      - "./certs:/certs:ro"
      - "./instance:/lm/instance:ro"
      - "./settings.conf:/lm/settings.conf:ro" # default settings
      - "data_workflows:/var/data/lm"
    ports:
      - "8001:8000"
    networks:
      - life_monitor

  redis:
    image: bitnami/redis:6.2
    ports:
      - "6379"
    env_file: *env_file
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
    networks:
      - life_monitor
    volumes:
      - "data_redis:/bitnami/redis/data"

volumes:
  data_db:
  data_static_files:
  data_specs:
  data_redis:
  data_workflows:


networks:
  life_monitor:
    # You can easily connect this docker-compose with a
    # local instance of the Seek/WorkflowHub docker-compose by putting them
    # both on the same Docker network.  The configuration below will
    # instantiate the life monitor services on a docker network called
    # `life_monitor` which is owned and managed by the LifeMonitor docker-compose.
    # To connect LifeMonitor to an existing network, set the property `name` below
    # to the name of the network name you'd like to connect and set
    # the property `external` to `true`, to declare the network as externally managed.
    # See the docker-compose network configuration reference for more details.
    name: life_monitor
    external: false
    # If are not using an external network, you can customize
    # the network address by uncommenting the lines below
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 192.168.238.0/24
