global:
  evaluation_interval: 1m
  scrape_interval: 10s
  scrape_timeout: 10s
rule_files:
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: lifemonitor
  static_configs:
  - targets:
    - metrics:9091
# - job_name: dramatiq_worker
#   static_configs:
#   - targets:
#     - worker:9191
# alerting:
#   alertmanagers:
#   - kubernetes_sd_configs:
#       - role: pod
#     tls_config:
#       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#     relabel_configs:
#     - source_labels: [__meta_kubernetes_namespace]
#       regex: monitoring
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_label_app]
#       regex: prometheus
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_label_component]
#       regex: alertmanager
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_probe]
#       regex: .*
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_container_port_number]
#       regex:
#       action: drop
