{
 "title": "LifeMonitor Dashboard: Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  { "title": "LifeMonitor Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "stat",
   "description": "Number of users registered on this LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_users{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "stat",
   "description": "Number of workflows registered on this LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflows{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Versions",
   "type": "stat",
   "description": "Number of workflow versions registered on this LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflow_versions{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Registries",
   "type": "stat",
   "description": "Number of Workflow registries registered on the LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflow_registries{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Suites",
   "type": "stat",
   "description": "Number of workflow suites registered on the LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflow_suites{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Test Instances",
   "type": "stat",
   "description": "Number of workflow test instances registered on the LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflow_test_instances{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LifeMonitor WebApp Active Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Active WebApp Clients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lifemonitor_webapp_proxy_http_websocket_connections_total{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Localisation of Active WebApp Clients",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "lifemonitor_webapp_proxy_http_websocket_connections_total{environment=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LifeMonitor Back-end Active Connections and Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Active Http Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lifemonitor_api_proxy_http_connection_status{environment=\"$environment\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Location",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(country_long, country_short, city, latitude, longitude) (lifemonitor_api_proxy_http_connection_requests{environment=\"$environment\", request!=\"/metrics\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Requests Success/Failure %",
   "type": "piechart",
   "description": "Percentage of request errors by type",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(status) (lifemonitor_api_proxy_http_connection_requests{environment=\"$environment\", status=~\"2.*\", upstream_address!=\"-\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum by() (lifemonitor_api_proxy_http_requests_error_total{environment=\"$environment\", upstream_address!=\"-\", status!~\"2.+\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(lifemonitor_api_http_request_total{environment=\"$environment\"}[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  }
 ]
}