{
 "title": "LifeMonitor Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  { "title": "LifeMonitor Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "stat",
   "description": "Number of users registered on this LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_users{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "stat",
   "description": "Number of workflows registered on this LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflows{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Versions",
   "type": "stat",
   "description": "Number of workflow versions registered on this LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflow_versions{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Registries",
   "type": "stat",
   "description": "Number of Workflow registries registered on the LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflow_registries{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Suites",
   "type": "stat",
   "description": "Number of workflow suites registered on the LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflow_suites{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Test Instances",
   "type": "stat",
   "description": "Number of workflow test instances registered on the LifeMonitor instance",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lifemonitor_api_workflow_test_instances{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LifeMonitor WebApp Active Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Active Web App Clients",
   "type": "gauge",
   "description": "Number of Current Users on the Web App",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lifemonitor_webapp_http_websocket_connections_total{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Location of Active Web App Clients",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lifemonitor_webapp_http_websocket_connections_total{environment=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of LifeMonitor WebApp HTTP Connections to Back-end API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Requests by Country",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(client_country_long) (rate(lifemonitor_webapp_http_requests_total{environment=\"$environment\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 200",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(lifemonitor_webapp_http_connections{status=\"200\", environment=\"$environment\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status ~= 3**",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(lifemonitor_webapp_http_connections{status=~\"3[0-9][0-9]\", environment=\"$environment\"}[0-9][0-9]\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status ~= 4**",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(lifemonitor_webapp_http_connections{status=~\"4[0-9][0-9]\", environment=\"$environment\"}[0-9][0-9]\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status ~= 5**",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(lifemonitor_webapp_http_connections{status=~\"5[0-9][0-9]\", environment=\"$environment\"}[0-9][0-9]\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebApp Http Connections to Back-end API by status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "WebApp HTTP Connections 200 status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (lifemonitor_webapp_http_connections{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Direct API Back-end Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Active HTTP Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(lifemonitor_api_proxy_http_connection_status{state=\"active\", environment=\"$environment\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Upstream Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "increase(lifemonitor_api_proxy_http_connection_requests{upstream_address!=\"-\", request!=\"/metrics\", environment=\"$environment\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests by Country",
   "type": "piechart",
   "description": "Number of Active Clients By Country",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(country_long) (increase(lifemonitor_api_proxy_http_connection_requests{request!=\"/metrics\", environment=\"$environment\"}[30s]))",
     "legendFormat": "{{country_long}}"
    }
   ]
  },
  {
   "title": "% Request Errors",
   "type": "piechart",
   "description": "Percentage of request errors by type",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(lifemonitor_api_proxy_http_requests_error_total{environment=\"$environment\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LifeMonitor API Backend Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(lifemonitor_api_http_request_total{environment=\"$environment\"}[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lifemonitor_api_http_request_duration_seconds_count{status=\"200\", environment=\"$environment\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(lifemonitor_api_http_request_duration_seconds_count{status!=\"200\", environment=\"$environment\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lifemonitor_api_http_request_duration_seconds_sum{status=\"200\", environment=\"$environment\"}[30s]) / rate(lifemonitor_api_http_request_duration_seconds_count{status=\"200\", environment=\"$environment\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(lifemonitor_api_http_request_duration_seconds_bucket{status=\"200\", le=\"0.25\", environment=\"$environment\"}[30s]) / ignoring(le) increase(lifemonitor_api_http_request_duration_seconds_count{status=\"200\", environment=\"$environment\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(lifemonitor_api_http_request_duration_seconds_bucket{status=\"200\", environment=\"$environment\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(lifemonitor_api_http_request_duration_seconds_bucket{status=\"200\", environment=\"$environment\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}