{
 "title": "LifeMonitor Dashboard: Front-end",
 "description": "Dashboard to monitor to the LifeMonitor Back-end",
 "tags": [
  "monitoring",
  "lifemonitor",
  "back-end"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  { "title": "Active WebApp Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active WebApp Clients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lifemonitor_webapp_proxy_http_websocket_connections_total{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Localisation of Active WebApp Clients",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "lifemonitor_webapp_proxy_http_websocket_connections_total{environment=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebApp Connections and Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Requests Location",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(country_long, country_short, city, latitude, longitude) (lifemonitor_webapp_proxy_http_connection_requests{environment=\"$environment\", request!=\"/metrics\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Active Http Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lifemonitor_webapp_proxy_http_connection_status{environment=\"$environment\", state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of HTTP Connections by state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "sum by(state) (lifemonitor_webapp_proxy_http_connection_status{environment=\"$environment\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Upstream Connection Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(lifemonitor_webapp_proxy_http_connection_requests{environment=\"$environment\", upstream_address!=\"-\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Country",
   "type": "piechart",
   "description": "Number of requests By Country",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(country_long) (lifemonitor_webapp_proxy_http_connection_requests{environment=\"$environment\", upstream_address!=\"-\"})",
     "legendFormat": "{{country_long}}"
    }
   ]
  },
  {
   "title": "Requests Success/Failure %",
   "type": "piechart",
   "description": "Percentage of request errors by type",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(status) (lifemonitor_webapp_proxy_http_connection_requests{environment=\"$environment\", status=~\"2.*\", upstream_address!=\"-\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum by() (lifemonitor_webapp_proxy_http_connection_requests{environment=\"$environment\", upstream_address!=\"-\", status!~\"2.+\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "% Request Errors",
   "type": "piechart",
   "description": "Percentage of request errors by type",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(status) (lifemonitor_webapp_proxy_http_connection_requests{environment=\"$environment\", upstream_address!=\"-\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance of API Back-end Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(lifemonitor_api_http_request_total{environment=\"$environment\"}[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lifemonitor_api_http_request_duration_seconds_count{status=\"200\", environment=\"$environment\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(lifemonitor_api_http_request_duration_seconds_count{status!=\"200\", environment=\"$environment\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lifemonitor_api_http_request_duration_seconds_sum{status=\"200\", environment=\"$environment\"}[30s]) / rate(lifemonitor_api_http_request_duration_seconds_count{status=\"200\", environment=\"$environment\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(lifemonitor_api_http_request_duration_seconds_bucket{status=\"200\", le=\"0.25\", environment=\"$environment\"}[30s]) / ignoring(le) increase(lifemonitor_api_http_request_duration_seconds_count{status=\"200\", environment=\"$environment\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(lifemonitor_api_http_request_duration_seconds_bucket{status=\"200\", environment=\"$environment\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(lifemonitor_api_http_request_duration_seconds_bucket{status=\"200\", environment=\"$environment\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}