# Copyright (c) 2020-2024 CRS4
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Add uuid property to notification model

Revision ID: 505e4e6976de
Revises: 296634f13bc4
Create Date: 2022-01-27 11:43:27.119562

"""
from alembic import op
import sqlalchemy as sa
from lifemonitor.models import UUID
import uuid as _uuid

# revision identifiers, used by Alembic.
revision = '505e4e6976de'
down_revision = '296634f13bc4'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    notifications = bind.execute("SELECT id FROM notification")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('uuid', UUID(), nullable=True))
    for n in notifications:
        bind.execute(f"UPDATE notification SET uuid = '{_uuid.uuid4()}' WHERE id = {n[0]}")
    op.alter_column('notification', 'uuid', nullable=False)
    op.create_index(op.f('ix_notification_uuid'), 'notification', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_uuid'), table_name='notification')
    op.drop_column('notification', 'uuid')
    # ### end Alembic commands ###
