"""Enable workflow visibility

Revision ID: 6086cb72f9e1
Revises: 7aa503323413
Create Date: 2021-10-11 16:30:46.588247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6086cb72f9e1'
down_revision = '7aa503323413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.add_column('workflow', sa.Column('public', sa.Boolean(), nullable=True))
    bind.execute("UPDATE workflow set public = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'public')
    # ### end Alembic commands ###
