"""Change Notification.type::str to Notification.event::EventType

Revision ID: a46c90bedbbf
Revises: 24c34681f538
Create Date: 2022-01-24 09:27:57.815975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46c90bedbbf'
down_revision = '24c34681f538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('event', sa.Integer(), nullable=False))
    op.drop_column('notification', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notification', 'event')
    # ### end Alembic commands ###
