# Copyright (c) 2020-2024 CRS4
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Hosting Service

Revision ID: bbe1397dc8a9
Revises: 8b2e530dc029
Create Date: 2021-09-03 07:33:30.999951

"""
import logging

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bbe1397dc8a9'
down_revision = '8b2e530dc029'
branch_labels = None
depends_on = None

# set logger
logger = logging.getLogger('alembic.env')


def upgrade():
    bind = op.get_bind()
    registries = bind.execute("SELECT id FROM workflow_registry")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosting_service',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['resource.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('workflow_registry_id_fkey', 'workflow_registry', type_='foreignkey')

    for r in registries:
        logger.info(r[0])
        bind.execute(f"INSERT INTO hosting_service (id) VALUES ({r[0]})")

    # set foreign key workflow_registry -> hosting_service
    op.create_foreign_key(None, 'workflow_registry', 'hosting_service', ['id'], ['id'])

    # insert github hosting service
    r = bind.execute("SELECT * from oauth2_identity_provider WHERE name = 'github'")
    data = r.fetchall()
    if len(data) == 1:
        github_data = data[0]
        r = bind.execute("select nextval('resource_id_seq')")
        r_id = r.fetchall()[0][0]
        bind.execute(f"INSERT INTO resource (id,uuid,type,name,uri) VALUES ({r_id},gen_random_uuid(),'hosting_service','github','https://github.com')")
        bind.execute(f"INSERT INTO hosting_service (id,server_id) VALUES ({r_id},{github_data[0]})")

    # Fix relationship RO-Crate->HostingService
    op.drop_constraint("ro_crate_hosting_service_id_fkey", 'ro_crate', type_='foreignkey')
    op.create_foreign_key("ro_crate_hosting_service_id_fkey", 'ro_crate', 'hosting_service', ['hosting_service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # Fix relationship RO-Crate->HostingService
    op.drop_constraint("ro_crate_hosting_service_id_fkey", 'ro_crate', type_='foreignkey')
    op.create_foreign_key("ro_crate_hosting_service_id_fkey", 'ro_crate', 'resource', ['hosting_service_id'], ['id'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("workflow_registry_id_fkey", 'workflow_registry', type_='foreignkey')
    op.create_foreign_key('workflow_registry_id_fkey', 'workflow_registry', 'resource', ['id'], ['id'])
    op.drop_table('hosting_service')

    # ### end Alembic commands ###
