"""Add settings property to user model

Revision ID: fc06761a2da4
Revises: 52561c782d96
Create Date: 2022-03-17 00:02:18.650341

"""
from alembic import op
import sqlalchemy as sa
from lifemonitor.models import JSON


# revision identifiers, used by Alembic.
revision = 'fc06761a2da4'
down_revision = '52561c782d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings', JSON(), nullable=True))
    bind = op.get_bind()
    bind.execute('UPDATE "user" SET settings=\'{}\'')
    op.alter_column('user', 'settings', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'settings')
    # ### end Alembic commands ###
