
# vim: set et sw=2

openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Life Monitor API"
  description: "Workflow sustainability service"

servers:
    - url: /
      description: Version 0.0 of API.  Add version prefix (e.g, /v1.0) once we have something useful
 
paths:
  /workflows:
    get:
      operationId: "api.workflows_get"
      summary: "Get all known workflows"
      responses:
        '200':
          description: A JSON array of Workflow objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workflow'

    post:
      operationId: "api.workflows_post"
      summary: "Register a workflow"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workflow'
      responses:
        '201':
          description: Workflow created

  /workflows/{wf_id}:
    get:
      operationId: "api.workflows_get_by_id"
      summary: "Get information about a single workflow"
      parameters:
        - $ref: '#/components/parameters/wf_id'
      responses:
        '200':
          description: A Workflow object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          description: Invalid input
        '404':
          description: Not found

    put:
      operationId: "api.workflows_put"
      summary: "Modify an existing workflow"
      parameters:
        - $ref: '#/components/parameters/wf_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workflow'
      responses:
        '200':
          description: Workflow updated

    delete:
      operationId: "api.workflows_delete"
      summary: "Delete a workflow"
      parameters:
        - $ref: '#/components/parameters/wf_id'
      responses:
        '200':
          description: Does not exist
        '204':
          description: Deleted
        '400':
          description: Invalid input

components:
  parameters:
    wf_id:
      name: "wf_id"
      description: "Workflow's Unique identifier"
      in: path
      schema:
        type: string
      required: true

  schemas:
    Workflow:
      type: object
      properties:
        name:
          type: string
      required:
        - name
