apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.fullname" . }}-backend
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.lifemonitor.autoscaling.enabled }}
  replicas: {{ .Values.lifemonitor.replicaCount }}
  serviceName: "lifemonitor-backend"
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      annotations:
        checksum/settings: {{ include (print $.Template.BasePath "/settings.secret.yaml") . | sha256sum }}
      {{- with .Values.lifemonitor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}       
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
        {{- if $.Values.monitoring.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'metrics'
        prometheus.io/port: '9090'
        prometheus.io/scheme: 'http'
        {{- end }}
    spec:
      {{- with .Values.lifemonitor.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.lifemonitor.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-backend
          securityContext:
            {{- toYaml .Values.lifemonitor.securityContext | nindent 12 }}
          image: {{ include "chart.lifemonitor.image" . }}
          imagePullPolicy: {{ .Values.lifemonitor.imagePullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              wait-for-redis.sh && wait-for-postgres.sh
              ./lm-admin db wait-for-db
          env:
          {{- include "lifemonitor.common-env" . | nindent 12 }}
          volumeMounts:
          {{- include "lifemonitor.common-volume-mounts" . | nindent 12 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.lifemonitor.securityContext | nindent 12 }}
          image: {{ include "chart.lifemonitor.image" . }}
          imagePullPolicy: {{ .Values.lifemonitor.imagePullPolicy }}
          env:
          {{- include "lifemonitor.common-env" . | nindent 12 }}
          volumeMounts:
          {{- include "lifemonitor.common-volume-mounts" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: 8000
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            {{- toYaml .Values.lifemonitor.resources | nindent 12 }}
      volumes:
      {{- include "lifemonitor.common-volume" . | nindent 8 }}
      {{- with .Values.lifemonitor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lifemonitor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lifemonitor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
