{{- if or (.Values.maintenanceMode.enabled) (.Values.console.enabled ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-console
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.lifemonitor.autoscaling.enabled }}
  replicas: {{ .Values.lifemonitor.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/settings: {{ include (print $.Template.BasePath "/settings.secret.yaml") . | sha256sum }}
      {{- with .Values.lifemonitor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}       
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.lifemonitor.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.lifemonitor.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.lifemonitor.securityContext | nindent 12 }}
          image: {{ include "chart.lifemonitor.image" . }}
          imagePullPolicy: {{ .Values.lifemonitor.imagePullPolicy }}
          command: ["/bin/sh","-c"]
          args: ["wait-for-redis.sh && wait-for-postgres.sh && sleep infinity"]
          env:
          {{- include "lifemonitor.common-env" . | nindent 12 }}
            - name: LIFEMONITOR_MAINTENANCE_MODE
              value: {{ .Values.maintenanceMode.enabled | quote }}
            - name: LIFEMONITOR_CONSOLE_ENABLED
              value: {{ .Values.console.enabled | quote }}
          volumeMounts:
          {{- include "lifemonitor.common-volume-mounts" . | nindent 12 }}
            - name: lifemonitor-backup
              mountPath: "/var/data/backup"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP         
          resources:
            {{- toYaml .Values.lifemonitor.resources | nindent 12 }}
      volumes:
        - name: lifemonitor-backup
          persistentVolumeClaim:
            claimName: {{ .Values.backup.existingClaim }}
      {{- include "lifemonitor.common-volume" . | nindent 8 }}
      {{- with .Values.lifemonitor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lifemonitor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lifemonitor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}