{{- $dataWorkflowsExists := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace ( include "chart.lifemonitor.data.workflows" . ) ) }}
{{- if not $dataWorkflowsExists }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.lifemonitor.data.workflows" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.global.readWriteManyStorageClass }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end -}}