apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-init
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: lifemonitor-init
        image: "{{ .Values.lifemonitor.image }}"
        imagePullPolicy: {{ .Values.lifemonitor.imagePullPolicy }}
        command: ["/bin/sh","-c"]
        args: ["wait-for-postgres.sh && flask db init"]
        env:
{{ include "lifemonitor.common-env" . | indent 10 }}
        volumeMounts:
{{ include "lifemonitor.common-volume-mounts" . | indent 10 }}
      restartPolicy: Never
      volumes:
{{ include "lifemonitor.common-volume" . | indent 8 }}
       {{- with .Values.lifemonitor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lifemonitor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lifemonitor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 4