apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-settings
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  settings.conf: |-
    # Environment settings
    FLASK_ENV={{- .Values.lifemonitor.environment }}
    LOG_LEVEL={{- .Values.lifemonitor.log_level | default "INFO" }}

    {{- if .Values.externalServerName }}
    # The name and port number of the server (e.g.: 'lm.local:8000'),
    # used as base_url on all the links returned by the API
    EXTERNAL_SERVER_URL={{ .Values.externalServerName }}
    {{- end }}

    # Normally, OAuthLib will raise an InsecureTransportError if you attempt to use OAuth2 over HTTP,
    # rather than HTTPS. Setting this environment variable will prevent this error from being raised.
    # This is mostly useful for local testing, or automated tests. Never set this variable in production.
    #AUTHLIB_INSECURE_TRANSPORT = True

    # Uncomment to use an additional config file to configure your LifeMonitor instance.
    # Variables defined here will override those in the default configuration.
    # The path should be absolute or relative to the instance folder
    # FLASK_APP_CONFIG_FILE=lm.py
    # Uncomment to override the default instance path folder. Only absolute paths are allowed.
    # FLASK_APP_INSTANCE_PATH=/home/lm/config_instance

    # PostgreSQL DBMS settings
    #POSTGRESQL_HOST={{ include "chart.fullname" . }}-postgresql
    POSTGRESQL_PORT={{ .Values.postgresql.service.port }}
    POSTGRESQL_DATABASE={{ .Values.postgresql.postgresqlDatabase }}
    POSTGRESQL_USERNAME={{ .Values.postgresql.postgresqlUsername }}
    POSTGRESQL_PASSWORD={{ .Values.postgresql.postgresqlPassword }}

    # Set admin credentials
    LIFEMONITOR_ADMIN_PASSWORD={{ .Values.lifemonitor.administrator.password }}

    # Gunicorn settings
    GUNICORN_WORKERS=1
    GUNICORN_THREADS=2

    {{- if and .Values.identity_providers.github .Values.identity_providers.github.client_id .Values.identity_providers.github.client_secret }}
    # Github OAuth2 settings
    GITHUB_CLIENT_ID="{{ .Values.identity_providers.github.client_id }}"
    GITHUB_CLIENT_SECRET="{{ .Values.identity_providers.github.client_secret }}"
    {{- end }}

    # Set tokens for testingService
    {{- if .Values.testing_services -}}
    {{- range $k, $v := .Values.testing_services }}
    {{ $k | upper }}_TESTING_SERVICE_URL={{ $v.api_url }}
    {{ $k | upper }}_TESTING_SERVICE_TOKEN={{ $v.token }}
    {{- end }}
    {{- end }}