apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-settings 
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  settings.conf: |-
    # environment properties

    # Uncomment these if you want to run with the development/debug features activated
    DEBUG=true
    #FLASK_ENV=development # set to 'production' by default
    LOG_LEVEL=DEBUG

    # Normally, OAuthLib will raise an InsecureTransportError if you attempt to use OAuth2 over HTTP,
    # rather than HTTPS. Setting this environment variable will prevent this error from being raised.
    # This is mostly useful for local testing, or automated tests. Never set this variable in production.
    #AUTHLIB_INSECURE_TRANSPORT = True

    # Uncomment to use an additional config file to configure your LifeMonitor instance.
    # Variables defined here will override those in the default configuration.
    # The path should be absolute or relative to the instance folder
    # FLASK_APP_CONFIG_FILE=lm.py
    # Uncomment to override the default instance path folder. Only absolute paths are allowed.
    # FLASK_APP_INSTANCE_PATH=/home/lm/config_instance

    # PostgreSQL DBMS settings
    #POSTGRESQL_HOST={{ include "chart.fullname" . }}-postgresql
    POSTGRESQL_PORT={{ .Values.postgresql.service.port }}
    POSTGRESQL_DATABASE={{ .Values.postgresql.postgresqlDatabase }}
    POSTGRESQL_USERNAME={{ .Values.postgresql.postgresqlUsername }}
    POSTGRESQL_PASSWORD={{ .Values.postgresql.postgresqlPassword }}

    # Gunicorn settings
    GUNICORN_WORKERS=1
    GUNICORN_THREADS=2

    # Github OAuth2 settings
    #GITHUB_CLIENT_ID="___YOUR_GITHUB_OAUTH2_CLIENT_ID___"
    #GITHUB_CLIENT_SECRET="___YOUR_GITHUB_OAUTH2_CLIENT_SECRET___"
