{{- $existingTLS := (lookup "v1" "Secret" .Release.Namespace ( include "chart.lifemonitor.tls" . )) }}
{{- if not $existingTLS }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.lifemonitor.tls" . }}
type: kubernetes.io/tls
data:
{{ ( include "gen-certs" . ) | indent 2 }}
{{- end -}}