{{- range $i, $queue := .Values.worker.queues }}

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" $ }}-worker-{{ $queue.name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  {{- if not $.Values.worker.autoscaling.enabled }}
  replicas: {{ $.Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/settings: {{ include (print $.Template.BasePath "/settings.secret.yaml") $ | sha256sum }}
      {{- with $.Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" $ | nindent 8 }}
        {{- if $.Values.monitoring.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'metrics'
        prometheus.io/port: '9191'
        prometheus.io/scheme: 'http'
        {{- end }}        
    spec:
      {{- with $.Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.worker.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          securityContext:
            {{- toYaml $.Values.lifemonitor.securityContext | nindent 12 }}
          image: {{ include "chart.lifemonitor.image" $ }}
          imagePullPolicy: {{ $.Values.lifemonitor.imagePullPolicy }}
          command: ["/bin/sh","-c"]
          args: ["wait-for-redis.sh && wait-for-postgres.sh && ./lm-admin db wait-for-db"]
          env:
          {{- include "lifemonitor.common-env" $ | nindent 12 }}
          volumeMounts:
          {{- include "lifemonitor.common-volume-mounts" $ | nindent 12 }}
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
      containers:
        - name: worker
          securityContext:
            {{- toYaml $.Values.worker.securityContext | nindent 12 }}
          {{- if $queue.image }}
          image: {{ $queue.image }}
          {{ else }}
          image: {{ include "chart.lifemonitor.image" $ }}
          {{- end }}
          imagePullPolicy: {{ $.Values.worker.imagePullPolicy }}
          command: ["/bin/sh","-c"]
          args: ["/usr/local/bin/worker_entrypoint.sh"]
          env:
          {{- include "lifemonitor.common-env" $ | nindent 12 }}
            - name: WORKER_QUEUES            
              {{if eq $queue.name "all" }}
              value:
              {{ else }}
              value: {{ $queue.name }}
              {{ end }}
          ports:
            - containerPort: 9191
          volumeMounts:
          {{- include "lifemonitor.common-volume-mounts" $ | nindent 12 }}
          # livenessProbe:
          #   httpGet:
          #     scheme: HTTPS
          #     path: /health
          #     port: 8000
          # readinessProbe:
          #   httpGet:
          #     scheme: HTTPS
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 3
          resources:
            {{- toYaml $.Values.worker.resources | nindent 12 }}
        {{- if $.Values.monitoring.loki.enabled }}
        - name: log-exporter
          image: {{ $.Values.monitoring.loki.logExporterImage }}
          args:
            - "-config.file=/etc/promtail/promtail.yaml" # Found in the ConfigMap
          resources:
            requests:
              memory: 128Mi
              cpu: 0.1
            limits:
              memory: 256Mi
              cpu: 0.2
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
            - name: lifemonitor-logs
              mountPath: /var/log
        {{- end }}
      volumes:
      {{- include "lifemonitor.common-volume" $ | nindent 8 }}
      {{- if $.Values.monitoring.loki.enabled }}
        - name: promtail-config
          configMap:
            name: "{{$.Release.Name}}-promtail-worker-{{ $queue.name }}-configmap"
      {{- end }}
      {{- with $.Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}