name: Gen docs index

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - gh-pages
#    paths:
#      - "!./docs_index.md"


env:
  TERM: xterm
jobs:
  make_docs_index:
    name: Generate and publish the Markdown documentation index
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python v${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mistletoe
        run: pip3 install mistletoe
      - name: Create index
        run: |
          rm -f ./docs_index.md
          ./make_docs_index.py -v --skip index.md
      - name: Push index
        run: |
          git config --global user.name "github-bot"
          git config --global user.email "username@users.noreply.github.com"
          git add docs_index.md
          # if there are no changes to the index, don't try to commit
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Generated docs index"
            git push 
          fi
