# This is a basic workflow to help you get started with Actions

name: Generate OpenAPI docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Gen docs
      run: docker run -u $(id -u):$(id -g)  --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -g html -i /local/lifemonitor/api.yaml -o /local/html/

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        # https://github.com/marketplace/actions/github-pages-action
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        # this attribute is still in beta -> destination_dir: spec_html 
  
